version: 2
general_options: &general_options
  docker:
    - image: circleci/node:12
  working_directory: ~/repo
jobs:
  checkout:
    <<: *general_options
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  lint:
    <<: *general_options
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Lint code
          command: npm run lint
  dry-compile:
    <<: *general_options
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Compile ts
          command: npm run check
  build:
    <<: *general_options
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build product
          command: npm run build -- --mode production
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  deploy-production:
    <<: *general_options
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Deploy production to firebase
          command: npx firebase-tools deploy --token $FIREBASE_TOKEN --project $FIREBASE_PROJECT_ID --only hosting
  build-storybook:
    <<: *general_options
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build storybook
          command: npm run build:storybook
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  deploy-storybook:
    <<: *general_options
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Deploy storybook to firebase
          command: npx firebase-tools deploy --token=$FIREBASE_TOKEN --project=$FIREBASE_STORYBOOK_PROJECT_ID --only hosting --public puclic_storybook
workflows:
  version: 2
  default:
    jobs:
      - checkout
      - lint:
          requires:
            - checkout
      - dry-compile:
          requires:
            - checkout
      - build:
          requires:
            - lint
            - dry-compile
      - deploy-production:
          filters:
            branches:
              only: master
          requires:
            - build
      - build-storybook:
          requires:
            - lint
            - dry-compile
      - deploy-storybook:
          filters:
            branches:
              only: master
          requires:
            - build-storybook
